[package]
name = "minesweeper"
version = "0.1.0"
authors = ["MJ <will@ponsonby.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.1"
termion="1.5"
